[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
mvp_contributoor = "2Gy7qY6QX6cBF6WDXY4vssoskAq29witMf4JcSmh1jQd"

[programs.localnet]
mvp_contributoor = "4RZQo3d4HTy971QBHYorECL62y11jzJxsg5ppvCvrSbz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
shutdown_wait = 2000
upgradeable = false
